services:
  web:
    build: .
    container_name: django2_web
    ports:
      - "7788:8000"         # ðŸ‘ˆ æ”¹é€™è£¡ï¼Œè®“å®ƒç”¨ 7788
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    restart: always
